<?php
/**
 * BalanceResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DigitalFemsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DigitalFemsa\Model;

use \ArrayAccess;
use \DigitalFemsa\ObjectSerializer;

/**
 * BalanceResponse Class Doc Comment
 *
 * @category Class
 * @description Company balance summary.  Monetary fields are returned as arrays of amounts grouped by currency (see &#x60;balance_common_field&#x60; items).
 * @package  DigitalFemsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BalanceResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'balance_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'available' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'pending' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'retention_amount' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'retained' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'temporarily_retained' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'target_retention_amount' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'target_temporary_retention_amount' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'target_collateral_amount' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'gateway' => '\DigitalFemsa\Model\BalanceCommonField[]',
        'cashout_retention_debited' => '\DigitalFemsa\Model\BalanceCommonField[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'available' => null,
        'pending' => null,
        'retention_amount' => null,
        'retained' => null,
        'temporarily_retained' => null,
        'target_retention_amount' => null,
        'target_temporary_retention_amount' => null,
        'target_collateral_amount' => null,
        'gateway' => null,
        'cashout_retention_debited' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'available' => false,
        'pending' => false,
        'retention_amount' => false,
        'retained' => false,
        'temporarily_retained' => false,
        'target_retention_amount' => false,
        'target_temporary_retention_amount' => false,
        'target_collateral_amount' => false,
        'gateway' => false,
        'cashout_retention_debited' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'available' => 'available',
        'pending' => 'pending',
        'retention_amount' => 'retention_amount',
        'retained' => 'retained',
        'temporarily_retained' => 'temporarily_retained',
        'target_retention_amount' => 'target_retention_amount',
        'target_temporary_retention_amount' => 'target_temporary_retention_amount',
        'target_collateral_amount' => 'target_collateral_amount',
        'gateway' => 'gateway',
        'cashout_retention_debited' => 'cashout_retention_debited'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'available' => 'setAvailable',
        'pending' => 'setPending',
        'retention_amount' => 'setRetentionAmount',
        'retained' => 'setRetained',
        'temporarily_retained' => 'setTemporarilyRetained',
        'target_retention_amount' => 'setTargetRetentionAmount',
        'target_temporary_retention_amount' => 'setTargetTemporaryRetentionAmount',
        'target_collateral_amount' => 'setTargetCollateralAmount',
        'gateway' => 'setGateway',
        'cashout_retention_debited' => 'setCashoutRetentionDebited'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'available' => 'getAvailable',
        'pending' => 'getPending',
        'retention_amount' => 'getRetentionAmount',
        'retained' => 'getRetained',
        'temporarily_retained' => 'getTemporarilyRetained',
        'target_retention_amount' => 'getTargetRetentionAmount',
        'target_temporary_retention_amount' => 'getTargetTemporaryRetentionAmount',
        'target_collateral_amount' => 'getTargetCollateralAmount',
        'gateway' => 'getGateway',
        'cashout_retention_debited' => 'getCashoutRetentionDebited'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('available', $data ?? [], null);
        $this->setIfExists('pending', $data ?? [], null);
        $this->setIfExists('retention_amount', $data ?? [], null);
        $this->setIfExists('retained', $data ?? [], null);
        $this->setIfExists('temporarily_retained', $data ?? [], null);
        $this->setIfExists('target_retention_amount', $data ?? [], null);
        $this->setIfExists('target_temporary_retention_amount', $data ?? [], null);
        $this->setIfExists('target_collateral_amount', $data ?? [], null);
        $this->setIfExists('gateway', $data ?? [], null);
        $this->setIfExists('cashout_retention_debited', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['available'] === null) {
            $invalidProperties[] = "'available' can't be null";
        }
        if ($this->container['pending'] === null) {
            $invalidProperties[] = "'pending' can't be null";
        }
        if ($this->container['retention_amount'] === null) {
            $invalidProperties[] = "'retention_amount' can't be null";
        }
        if ($this->container['retained'] === null) {
            $invalidProperties[] = "'retained' can't be null";
        }
        if ($this->container['temporarily_retained'] === null) {
            $invalidProperties[] = "'temporarily_retained' can't be null";
        }
        if ($this->container['target_retention_amount'] === null) {
            $invalidProperties[] = "'target_retention_amount' can't be null";
        }
        if ($this->container['target_temporary_retention_amount'] === null) {
            $invalidProperties[] = "'target_temporary_retention_amount' can't be null";
        }
        if ($this->container['target_collateral_amount'] === null) {
            $invalidProperties[] = "'target_collateral_amount' can't be null";
        }
        if ($this->container['gateway'] === null) {
            $invalidProperties[] = "'gateway' can't be null";
        }
        if ($this->container['cashout_retention_debited'] === null) {
            $invalidProperties[] = "'cashout_retention_debited' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets available
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getAvailable()
    {
        return $this->container['available'];
    }

    /**
     * Sets available
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $available Amounts currently available, grouped by currency.
     *
     * @return self
     */
    public function setAvailable($available)
    {
        if (is_null($available)) {
            throw new \InvalidArgumentException('non-nullable available cannot be null');
        }
        $this->container['available'] = $available;

        return $this;
    }

    /**
     * Gets pending
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getPending()
    {
        return $this->container['pending'];
    }

    /**
     * Sets pending
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $pending Amounts pending settlement, grouped by currency.
     *
     * @return self
     */
    public function setPending($pending)
    {
        if (is_null($pending)) {
            throw new \InvalidArgumentException('non-nullable pending cannot be null');
        }
        $this->container['pending'] = $pending;

        return $this;
    }

    /**
     * Gets retention_amount
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getRetentionAmount()
    {
        return $this->container['retention_amount'];
    }

    /**
     * Sets retention_amount
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $retention_amount Retention amount applied, grouped by currency.
     *
     * @return self
     */
    public function setRetentionAmount($retention_amount)
    {
        if (is_null($retention_amount)) {
            throw new \InvalidArgumentException('non-nullable retention_amount cannot be null');
        }
        $this->container['retention_amount'] = $retention_amount;

        return $this;
    }

    /**
     * Gets retained
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getRetained()
    {
        return $this->container['retained'];
    }

    /**
     * Sets retained
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $retained Amounts currently retained, grouped by currency.
     *
     * @return self
     */
    public function setRetained($retained)
    {
        if (is_null($retained)) {
            throw new \InvalidArgumentException('non-nullable retained cannot be null');
        }
        $this->container['retained'] = $retained;

        return $this;
    }

    /**
     * Gets temporarily_retained
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getTemporarilyRetained()
    {
        return $this->container['temporarily_retained'];
    }

    /**
     * Sets temporarily_retained
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $temporarily_retained Amounts temporarily retained, grouped by currency.
     *
     * @return self
     */
    public function setTemporarilyRetained($temporarily_retained)
    {
        if (is_null($temporarily_retained)) {
            throw new \InvalidArgumentException('non-nullable temporarily_retained cannot be null');
        }
        $this->container['temporarily_retained'] = $temporarily_retained;

        return $this;
    }

    /**
     * Gets target_retention_amount
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getTargetRetentionAmount()
    {
        return $this->container['target_retention_amount'];
    }

    /**
     * Sets target_retention_amount
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $target_retention_amount Target retention amount, grouped by currency.
     *
     * @return self
     */
    public function setTargetRetentionAmount($target_retention_amount)
    {
        if (is_null($target_retention_amount)) {
            throw new \InvalidArgumentException('non-nullable target_retention_amount cannot be null');
        }
        $this->container['target_retention_amount'] = $target_retention_amount;

        return $this;
    }

    /**
     * Gets target_temporary_retention_amount
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getTargetTemporaryRetentionAmount()
    {
        return $this->container['target_temporary_retention_amount'];
    }

    /**
     * Sets target_temporary_retention_amount
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $target_temporary_retention_amount Target temporary retention amount, grouped by currency.
     *
     * @return self
     */
    public function setTargetTemporaryRetentionAmount($target_temporary_retention_amount)
    {
        if (is_null($target_temporary_retention_amount)) {
            throw new \InvalidArgumentException('non-nullable target_temporary_retention_amount cannot be null');
        }
        $this->container['target_temporary_retention_amount'] = $target_temporary_retention_amount;

        return $this;
    }

    /**
     * Gets target_collateral_amount
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getTargetCollateralAmount()
    {
        return $this->container['target_collateral_amount'];
    }

    /**
     * Sets target_collateral_amount
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $target_collateral_amount Target collateral amount, grouped by currency.
     *
     * @return self
     */
    public function setTargetCollateralAmount($target_collateral_amount)
    {
        if (is_null($target_collateral_amount)) {
            throw new \InvalidArgumentException('non-nullable target_collateral_amount cannot be null');
        }
        $this->container['target_collateral_amount'] = $target_collateral_amount;

        return $this;
    }

    /**
     * Gets gateway
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getGateway()
    {
        return $this->container['gateway'];
    }

    /**
     * Sets gateway
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $gateway Gateway balance amounts, grouped by currency.
     *
     * @return self
     */
    public function setGateway($gateway)
    {
        if (is_null($gateway)) {
            throw new \InvalidArgumentException('non-nullable gateway cannot be null');
        }
        $this->container['gateway'] = $gateway;

        return $this;
    }

    /**
     * Gets cashout_retention_debited
     *
     * @return \DigitalFemsa\Model\BalanceCommonField[]
     */
    public function getCashoutRetentionDebited()
    {
        return $this->container['cashout_retention_debited'];
    }

    /**
     * Sets cashout_retention_debited
     *
     * @param \DigitalFemsa\Model\BalanceCommonField[] $cashout_retention_debited Cashout retention debited amounts, grouped by currency.
     *
     * @return self
     */
    public function setCashoutRetentionDebited($cashout_retention_debited)
    {
        if (is_null($cashout_retention_debited)) {
            throw new \InvalidArgumentException('non-nullable cashout_retention_debited cannot be null');
        }
        $this->container['cashout_retention_debited'] = $cashout_retention_debited;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


