<?php
/**
 * TransfersResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DigitalFemsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DigitalFemsa\Model;

use \ArrayAccess;
use \DigitalFemsa\ObjectSerializer;

/**
 * TransfersResponse Class Doc Comment
 *
 * @category Class
 * @description A transfer represents the action of sending an amount to a business bank account including the status, amount and destination used to make the transfer.
 * @package  DigitalFemsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransfersResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'transfers_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'object' => 'string',
        'amount' => 'int',
        'created_at' => 'int',
        'currency' => 'string',
        'livemode' => 'bool',
        'status' => 'string',
        'statement_reference' => 'string',
        'statement_description' => 'string',
        'destination' => '\DigitalFemsa\Model\TransfersResponseDestination',
        'fee' => 'int',
        'capture_amount' => 'int',
        'capture_fee' => 'int',
        'capture_net' => 'int',
        'refund_amount' => 'int',
        'refund_fee' => 'int',
        'refund_net' => 'int',
        'payout_amount' => 'int',
        'payout_fee' => 'int',
        'payout_net' => 'int',
        'transactions' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'object' => null,
        'amount' => 'int64',
        'created_at' => 'int64',
        'currency' => null,
        'livemode' => null,
        'status' => null,
        'statement_reference' => null,
        'statement_description' => null,
        'destination' => null,
        'fee' => 'int64',
        'capture_amount' => 'int64',
        'capture_fee' => 'int64',
        'capture_net' => 'int64',
        'refund_amount' => 'int64',
        'refund_fee' => 'int64',
        'refund_net' => 'int64',
        'payout_amount' => 'int64',
        'payout_fee' => 'int64',
        'payout_net' => 'int64',
        'transactions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'object' => false,
        'amount' => false,
        'created_at' => false,
        'currency' => false,
        'livemode' => false,
        'status' => false,
        'statement_reference' => false,
        'statement_description' => false,
        'destination' => false,
        'fee' => true,
        'capture_amount' => true,
        'capture_fee' => true,
        'capture_net' => true,
        'refund_amount' => true,
        'refund_fee' => true,
        'refund_net' => true,
        'payout_amount' => true,
        'payout_fee' => true,
        'payout_net' => true,
        'transactions' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'object' => 'object',
        'amount' => 'amount',
        'created_at' => 'created_at',
        'currency' => 'currency',
        'livemode' => 'livemode',
        'status' => 'status',
        'statement_reference' => 'statement_reference',
        'statement_description' => 'statement_description',
        'destination' => 'destination',
        'fee' => 'fee',
        'capture_amount' => 'capture_amount',
        'capture_fee' => 'capture_fee',
        'capture_net' => 'capture_net',
        'refund_amount' => 'refund_amount',
        'refund_fee' => 'refund_fee',
        'refund_net' => 'refund_net',
        'payout_amount' => 'payout_amount',
        'payout_fee' => 'payout_fee',
        'payout_net' => 'payout_net',
        'transactions' => 'transactions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'object' => 'setObject',
        'amount' => 'setAmount',
        'created_at' => 'setCreatedAt',
        'currency' => 'setCurrency',
        'livemode' => 'setLivemode',
        'status' => 'setStatus',
        'statement_reference' => 'setStatementReference',
        'statement_description' => 'setStatementDescription',
        'destination' => 'setDestination',
        'fee' => 'setFee',
        'capture_amount' => 'setCaptureAmount',
        'capture_fee' => 'setCaptureFee',
        'capture_net' => 'setCaptureNet',
        'refund_amount' => 'setRefundAmount',
        'refund_fee' => 'setRefundFee',
        'refund_net' => 'setRefundNet',
        'payout_amount' => 'setPayoutAmount',
        'payout_fee' => 'setPayoutFee',
        'payout_net' => 'setPayoutNet',
        'transactions' => 'setTransactions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'object' => 'getObject',
        'amount' => 'getAmount',
        'created_at' => 'getCreatedAt',
        'currency' => 'getCurrency',
        'livemode' => 'getLivemode',
        'status' => 'getStatus',
        'statement_reference' => 'getStatementReference',
        'statement_description' => 'getStatementDescription',
        'destination' => 'getDestination',
        'fee' => 'getFee',
        'capture_amount' => 'getCaptureAmount',
        'capture_fee' => 'getCaptureFee',
        'capture_net' => 'getCaptureNet',
        'refund_amount' => 'getRefundAmount',
        'refund_fee' => 'getRefundFee',
        'refund_net' => 'getRefundNet',
        'payout_amount' => 'getPayoutAmount',
        'payout_fee' => 'getPayoutFee',
        'payout_net' => 'getPayoutNet',
        'transactions' => 'getTransactions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('livemode', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('statement_reference', $data ?? [], null);
        $this->setIfExists('statement_description', $data ?? [], null);
        $this->setIfExists('destination', $data ?? [], null);
        $this->setIfExists('fee', $data ?? [], null);
        $this->setIfExists('capture_amount', $data ?? [], null);
        $this->setIfExists('capture_fee', $data ?? [], null);
        $this->setIfExists('capture_net', $data ?? [], null);
        $this->setIfExists('refund_amount', $data ?? [], null);
        $this->setIfExists('refund_fee', $data ?? [], null);
        $this->setIfExists('refund_net', $data ?? [], null);
        $this->setIfExists('payout_amount', $data ?? [], null);
        $this->setIfExists('payout_fee', $data ?? [], null);
        $this->setIfExists('payout_net', $data ?? [], null);
        $this->setIfExists('transactions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['object'] === null) {
            $invalidProperties[] = "'object' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ((mb_strlen($this->container['currency']) > 3)) {
            $invalidProperties[] = "invalid value for 'currency', the character length must be smaller than or equal to 3.";
        }

        if ($this->container['livemode'] === null) {
            $invalidProperties[] = "'livemode' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['statement_reference'] === null) {
            $invalidProperties[] = "'statement_reference' can't be null";
        }
        if ($this->container['statement_description'] === null) {
            $invalidProperties[] = "'statement_description' can't be null";
        }
        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique identifier of the transfer.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets object
     *
     * @return string
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string $object Object name, which is transfer.
     *
     * @return self
     */
    public function setObject($object)
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount Amount in cents of the transfer.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param int $created_at Date and time of creation of the transfer in Unix format.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency The currency of the transfer. It uses the 3-letter code of ISO 4217.
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        if ((mb_strlen($currency) > 3)) {
            throw new \InvalidArgumentException('invalid length for $currency when calling TransfersResponse., must be smaller than or equal to 3.');
        }

        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets livemode
     *
     * @return bool
     */
    public function getLivemode()
    {
        return $this->container['livemode'];
    }

    /**
     * Sets livemode
     *
     * @param bool $livemode Indicates whether the transfer was created in live mode or test mode.
     *
     * @return self
     */
    public function setLivemode($livemode)
    {
        if (is_null($livemode)) {
            throw new \InvalidArgumentException('non-nullable livemode cannot be null');
        }
        $this->container['livemode'] = $livemode;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Code indicating transfer status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets statement_reference
     *
     * @return string
     */
    public function getStatementReference()
    {
        return $this->container['statement_reference'];
    }

    /**
     * Sets statement_reference
     *
     * @param string $statement_reference Reference number of the transfer.
     *
     * @return self
     */
    public function setStatementReference($statement_reference)
    {
        if (is_null($statement_reference)) {
            throw new \InvalidArgumentException('non-nullable statement_reference cannot be null');
        }
        $this->container['statement_reference'] = $statement_reference;

        return $this;
    }

    /**
     * Gets statement_description
     *
     * @return string
     */
    public function getStatementDescription()
    {
        return $this->container['statement_description'];
    }

    /**
     * Sets statement_description
     *
     * @param string $statement_description Description of the transfer.
     *
     * @return self
     */
    public function setStatementDescription($statement_description)
    {
        if (is_null($statement_description)) {
            throw new \InvalidArgumentException('non-nullable statement_description cannot be null');
        }
        $this->container['statement_description'] = $statement_description;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return \DigitalFemsa\Model\TransfersResponseDestination
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param \DigitalFemsa\Model\TransfersResponseDestination $destination destination
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return int|null
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param int|null $fee Total fee for the transfer (present only when requesting the 'details' expansion).
     *
     * @return self
     */
    public function setFee($fee)
    {
        if (is_null($fee)) {
            array_push($this->openAPINullablesSetToNull, 'fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets capture_amount
     *
     * @return int|null
     */
    public function getCaptureAmount()
    {
        return $this->container['capture_amount'];
    }

    /**
     * Sets capture_amount
     *
     * @param int|null $capture_amount Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setCaptureAmount($capture_amount)
    {
        if (is_null($capture_amount)) {
            array_push($this->openAPINullablesSetToNull, 'capture_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('capture_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['capture_amount'] = $capture_amount;

        return $this;
    }

    /**
     * Gets capture_fee
     *
     * @return int|null
     */
    public function getCaptureFee()
    {
        return $this->container['capture_fee'];
    }

    /**
     * Sets capture_fee
     *
     * @param int|null $capture_fee Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setCaptureFee($capture_fee)
    {
        if (is_null($capture_fee)) {
            array_push($this->openAPINullablesSetToNull, 'capture_fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('capture_fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['capture_fee'] = $capture_fee;

        return $this;
    }

    /**
     * Gets capture_net
     *
     * @return int|null
     */
    public function getCaptureNet()
    {
        return $this->container['capture_net'];
    }

    /**
     * Sets capture_net
     *
     * @param int|null $capture_net Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setCaptureNet($capture_net)
    {
        if (is_null($capture_net)) {
            array_push($this->openAPINullablesSetToNull, 'capture_net');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('capture_net', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['capture_net'] = $capture_net;

        return $this;
    }

    /**
     * Gets refund_amount
     *
     * @return int|null
     */
    public function getRefundAmount()
    {
        return $this->container['refund_amount'];
    }

    /**
     * Sets refund_amount
     *
     * @param int|null $refund_amount Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setRefundAmount($refund_amount)
    {
        if (is_null($refund_amount)) {
            array_push($this->openAPINullablesSetToNull, 'refund_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('refund_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['refund_amount'] = $refund_amount;

        return $this;
    }

    /**
     * Gets refund_fee
     *
     * @return int|null
     */
    public function getRefundFee()
    {
        return $this->container['refund_fee'];
    }

    /**
     * Sets refund_fee
     *
     * @param int|null $refund_fee Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setRefundFee($refund_fee)
    {
        if (is_null($refund_fee)) {
            array_push($this->openAPINullablesSetToNull, 'refund_fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('refund_fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['refund_fee'] = $refund_fee;

        return $this;
    }

    /**
     * Gets refund_net
     *
     * @return int|null
     */
    public function getRefundNet()
    {
        return $this->container['refund_net'];
    }

    /**
     * Sets refund_net
     *
     * @param int|null $refund_net Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setRefundNet($refund_net)
    {
        if (is_null($refund_net)) {
            array_push($this->openAPINullablesSetToNull, 'refund_net');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('refund_net', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['refund_net'] = $refund_net;

        return $this;
    }

    /**
     * Gets payout_amount
     *
     * @return int|null
     */
    public function getPayoutAmount()
    {
        return $this->container['payout_amount'];
    }

    /**
     * Sets payout_amount
     *
     * @param int|null $payout_amount Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setPayoutAmount($payout_amount)
    {
        if (is_null($payout_amount)) {
            array_push($this->openAPINullablesSetToNull, 'payout_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payout_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payout_amount'] = $payout_amount;

        return $this;
    }

    /**
     * Gets payout_fee
     *
     * @return int|null
     */
    public function getPayoutFee()
    {
        return $this->container['payout_fee'];
    }

    /**
     * Sets payout_fee
     *
     * @param int|null $payout_fee Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setPayoutFee($payout_fee)
    {
        if (is_null($payout_fee)) {
            array_push($this->openAPINullablesSetToNull, 'payout_fee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payout_fee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payout_fee'] = $payout_fee;

        return $this;
    }

    /**
     * Gets payout_net
     *
     * @return int|null
     */
    public function getPayoutNet()
    {
        return $this->container['payout_net'];
    }

    /**
     * Sets payout_net
     *
     * @param int|null $payout_net Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setPayoutNet($payout_net)
    {
        if (is_null($payout_net)) {
            array_push($this->openAPINullablesSetToNull, 'payout_net');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payout_net', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payout_net'] = $payout_net;

        return $this;
    }

    /**
     * Gets transactions
     *
     * @return object[]|null
     */
    public function getTransactions()
    {
        return $this->container['transactions'];
    }

    /**
     * Sets transactions
     *
     * @param object[]|null $transactions Present only when requesting the 'details' expansion.
     *
     * @return self
     */
    public function setTransactions($transactions)
    {
        if (is_null($transactions)) {
            array_push($this->openAPINullablesSetToNull, 'transactions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transactions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transactions'] = $transactions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


