<?php
/**
 * PaymentMethodsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Femsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@Femsa.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Femsa\Test\Api;

use DigitalFemsa\Api\PaymentMethodsApi;
use DigitalFemsa\Configuration;
use DigitalFemsa\Model\CreateCustomerPaymentMethodsRequest;
use DigitalFemsa\Model\UpdatePaymentMethods;
use Femsa\Test\Api\BaseTest;
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use Psr\Http\Message\RequestInterface;
use PHPUnit\Framework\TestCase;

/**
 * PaymentMethodsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Femsa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentMethodsApiTest extends TestCase
{

    protected static PaymentMethodsApi $apiInstance;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        $host = getenv('BASE_PATH') ?: 'https://api.stg.digitalfemsa.io';
        $config = Configuration::getDefaultConfiguration()->setHost($host);
        self::$apiInstance = new PaymentMethodsApi(null, $config);
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCustomerPaymentMethods
     *
     * Create Payment Method.
     *
     */
    public function testCreateCustomerPaymentMethods()
    {
        echo "\n=== DEBUG: testCreateCustomerPaymentMethods ===\n";
        
        $accept_language = 'es';
        $rq = new CreateCustomerPaymentMethodsRequest([
            'type' => 'oxxo_recurrent',
            'token_id' => 'tokenID'
        ]);
        
        // Debug: Verificar objeto antes de enviar
        echo "\n1. Objeto CreateCustomerPaymentMethodsRequest creado:\n";
        echo "   - getType(): " . ($rq->getType() ?? 'NULL') . "\n";
        echo "   - getExpiresAt(): " . ($rq->getExpiresAt() ?? 'NULL') . "\n";
        
        // Debug: Serialización del objeto
        echo "\n2. Serialización del objeto:\n";
        echo "   - json_encode(): " . json_encode($rq) . "\n";
        echo "   - __toString(): " . $rq->__toString() . "\n";
        
        // Debug: Configurar Guzzle middleware para capturar request
        $container = [];
        $history = Middleware::history($container);
        $stack = HandlerStack::create();
        $stack->push($history);
        $stack->push(Middleware::mapRequest(function (RequestInterface $request) {
            echo "\n3. Request HTTP capturado por middleware:\n";
            echo "   - Method: " . $request->getMethod() . "\n";
            echo "   - URI: " . $request->getUri() . "\n";
            echo "   - Headers:\n";
            foreach ($request->getHeaders() as $name => $values) {
                echo "     * {$name}: " . implode(', ', $values) . "\n";
            }
            $body = (string) $request->getBody();
            echo "   - Body (" . strlen($body) . " bytes): {$body}\n";
            echo "   - Body hex: " . bin2hex($body) . "\n";
            return $request;
        }));
        
        // Crear cliente Guzzle con middleware
        $client = new Client(['handler' => $stack]);
        
        // Configurar API instance con cliente custom
        $config = Configuration::getDefaultConfiguration();
        $apiWithLogging = new PaymentMethodsApi($client, $config);
        
        try {
            $result = $apiWithLogging->createCustomerPaymentMethods('cus_2tXyF9BwPG14UMkkg', $rq, $accept_language);
            echo "\n4. Response exitoso\n";
            $this->assertNotEmpty($result, 'expected not empty result');
        } catch (\Exception $e) {
            echo "\n4. Exception capturada:\n";
            echo "   - Message: " . $e->getMessage() . "\n";
            echo "   - Code: " . $e->getCode() . "\n";
            if (method_exists($e, 'getResponseBody')) {
                echo "   - Response Body: " . $e->getResponseBody() . "\n";
            }
            throw $e;
        }
        
        echo "\n=== FIN DEBUG ===\n\n";
    }

    /**
     * Test case for deleteCustomerPaymentMethods
     *
     * Delete Payment Method.
     *
     */
    public function testDeleteCustomerPaymentMethods()
    {
        $accept_language = 'es';
        $result = self::$apiInstance->deleteCustomerPaymentMethods('cus_2tYENskzTjjgkGQLt', 'src_2tbd5Bgy67RL9oycM', $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for getCustomerPaymentMethods
     *
     * Get Payment Methods.
     *
     */
    public function testGetCustomerPaymentMethods()
    {
        $accept_language = 'es';
        $result = self::$apiInstance->getCustomerPaymentMethods('cus_2tYENskzTjjgkGQLt', $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }

    /**
     * Test case for updateCustomerPaymentMethods
     *
     * Update Payment Method.
     *
     */
    public function testUpdateCustomerPaymentMethods()
    {
        $accept_language = 'es';
        $rq = new UpdatePaymentMethods([
            'name' => 'test'
        ]);
        $result = self::$apiInstance->updateCustomerPaymentMethods('cus_2tYENskzTjjgkGQLt', 'src_2tbd5Bgy67RL9oycM', $rq, $accept_language);
        $this->assertNotEmpty($result, 'expected not empty result');
    }
}
